/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grooming_consultas;

/**
 *
 * @author LAP
 */
public class Consulta extends javax.swing.JFrame {

 public static double precio;
 public static String motivo; 
 public static String paquete; 
    public Consulta() {
        initComponents();
         this.setLocationRelativeTo(null);
         //necesito que uno de los 3 radio buton éste seleccionado al principio por lo que pondré primera vez
         
         rb_primera.setSelected(true); 
         
         //también necesito que lo que el cliente escriba en el texto se guarde en un documento
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rb_primera = new javax.swing.JRadioButton();
        rb_continuidad = new javax.swing.JRadioButton();
        rb_vacunacion = new javax.swing.JRadioButton();
        txt_motivo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bt_listo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grooming_consultas/trustme.gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("TIPO DE CONSULTA");

        buttonGroup1.add(rb_primera);
        rb_primera.setText("Primera vez");

        buttonGroup1.add(rb_continuidad);
        rb_continuidad.setText("Continuidad de tratamiento");

        buttonGroup1.add(rb_vacunacion);
        rb_vacunacion.setText("Vacunación");

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("¿Más detalles? Escribe abajo");

        bt_listo.setForeground(new java.awt.Color(0, 153, 153));
        bt_listo.setText("¡LISTO!");
        bt_listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_listoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_listo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_continuidad)
                                    .addComponent(rb_primera)
                                    .addComponent(rb_vacunacion))
                                .addGap(88, 88, 88)))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)
                        .addComponent(rb_primera)
                        .addGap(30, 30, 30)
                        .addComponent(rb_continuidad)
                        .addGap(30, 30, 30)
                        .addComponent(rb_vacunacion)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_listo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_listoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_listoActionPerformed
        // aquí necesito que cuando ponga listo lo mande a la ventana de perro
        
        
        
        Perro ventana= new Perro();
        ventana.setVisible(true);
        ventana.setDefaultCloseOperation(ventana.HIDE_ON_CLOSE);
        
        //además necesito poner los precios de las consultas dependiendo el tipo de consulta 
        
        double precio=0; //me dice que no la estoy usando, pero la uso abajo ¿no? 
        if(rb_primera.isSelected()){
            Consulta.precio=80;
        }
        if(rb_continuidad.isSelected()){
            Consulta.precio=120;
        }
        if(rb_vacunacion.isSelected()){
            Consulta.precio=100;
        }
        
       // además necesito darle valor a los botones
       rb_primera.setActionCommand("Primera consulta");
       rb_continuidad.setActionCommand("Consulta de seguimiento");
       rb_vacunacion.setActionCommand("Vacunación");
       
       Consulta.paquete=buttonGroup1.getSelection().getActionCommand();
       //y necesito que lo del text fiel se guarde en el texto, lo meteré en un string
       
        // String.motivo=null; ?? 
       
       //¿cómo le hago para lo que se escriba en el txt_motivo se guarde en mi string? 
       
       // if(txt_motivo!=null) 
       
       Consulta.motivo= txt_motivo.getText();
       
       
     
        
        
        
    }//GEN-LAST:event_bt_listoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_listo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rb_continuidad;
    private javax.swing.JRadioButton rb_primera;
    private javax.swing.JRadioButton rb_vacunacion;
    private javax.swing.JTextField txt_motivo;
    // End of variables declaration//GEN-END:variables
}
